font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
font_size 11.5

background #061322
foreground #d9f7ff
selection_background #12629a
selection_foreground #f4fcff
cursor #65dcff
cursor_text_color #061322
url_color #00c8ff

color0 #061322
color1 #ff7891
color2 #56e39f
color3 #f5cf65
color4 #207cdf
color5 #8d7df2
color6 #00c8ff
color7 #b8d9e8
color8 #32536b
color9 #ff9bad
color10 #7af0b7
color11 #ffe18a
color12 #65a9ff
color13 #b9aaff
color14 #65dcff
color15 #f4fcff

background_opacity 0.78
background_blur 24
dynamic_background_opacity yes
window_padding_width 12
window_border_width 0
draw_minimal_borders yes
confirm_os_window_close 0
enable_audio_bell no
tab_bar_style powerline
tab_powerline_style slanted
active_tab_background #00c8ff
active_tab_foreground #061322
inactive_tab_background #0b2c4a
inactive_tab_foreground #7ba7bd
shell_integration enabled
