color_theme = "kona-arch"
theme_background = false
truecolor = true
rounded_corners = true
terminal_sync = true
graph_symbol = "block"
graph_symbol_cpu = "block"
graph_symbol_gpu = "block"
graph_symbol_mem = "block"
graph_symbol_net = "block"
graph_symbol_proc = "tty"
shown_boxes = "cpu mem proc"
presets = "cpu:0:block,mem:0:block,proc:0:tty"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_colors = false
proc_gradient = false
proc_cpu_graphs = false
proc_info_smaps = false
cpu_single_graph = true
show_coretemp = false
show_cpu_watts = false
clock_format = ""
mem_graphs = false
show_swap = false
swap_disk = false
show_disks = true
show_io_stat = false
show_battery = false
background_update = false
save_config_on_exit = false
nvml_measure_pcie_speeds = false
