[general]
framerate = 30
bars = 24
autosens = 1

[input]
method = pipewire
source = auto

[output]
method = ncurses
channels = mono
mono_option = average
orientation = bottom

[color]
foreground = default
background = default

[smoothing]
noise_reduction = 74
integral = 70
gravity = 95
