background #171D29
foreground #F7FAFF
selection_background #2D405E
selection_foreground #F7FAFF
cursor #B5D2FF
cursor_text_color #10141C
url_color #7AA8F8
color0 #10141C
color1 #FF91A4
color2 #72DCB2
color3 #F2C879
color4 #7AA8F8
color5 #8D7DF2
color6 #A9C8FF
color7 #D6E3F5
color8 #9EACC0
color9 #FF91A4
color10 #72DCB2
color11 #F2C879
color12 #A9C8FF
color13 #B9AAFF
color14 #B5D2FF
color15 #293548
active_tab_background #8EB8FF
active_tab_foreground #10141C
inactive_tab_background #202A3A
inactive_tab_foreground #D6E3F5
